stages:
  - test
  - deploy

test:
  stage: test
  image: maven:3.8.8-eclipse-temurin-17
  script:
    - mvn clean verify -s $MAVEN_SETTINGS -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
  artifacts:
    when: always
    reports:
      junit:
        - "**/target/surefire-reports/*.xml"
  cache: 
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .m2/repository

deploy:
  stage: deploy
  image: maven:3.8.8-eclipse-temurin-17
  script: mvn deploy -s $MAVEN_SETTINGS
  cache: 
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .m2/repository
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: on_success
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
      when: manual
